base_url = "/"
compile_sass = true
title = "EFanZh’s Blog"

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
    { theme = "base16-ocean-light", filename = "../sass/style/syntax-theme-light.css" },
]

[[extra.links]]
title = "GitHub"
url = "https://github.com/EFanZh"
