name: Check
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: taiki-e/install-action@v2
            with:
                tool: zola
          - uses: actions/checkout@v4
          - run: zola check
