name: Publish
on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: taiki-e/install-action@v2
            with:
                tool: zola
          - uses: actions/checkout@v4
          - run: zola build -o _site
          - uses: actions/upload-pages-artifact@v2
    deploy:
        needs: build
        permissions:
            id-token: write
            pages: write
        runs-on: ubuntu-latest
        steps:
          - uses: actions/deploy-pages@v3
